### PR TITLE
Add universal model path via ENV_VAR, fix other issues on the way

### PR DESCRIPTION
**Pull request by d8ahazard**
If the VIDEO_MODEL_PATH env var is set, the app will use that path, instead of ./checkpoints.

This should address #36 

I also added a missing req. for SEINE, as well as fix an import conflict with the "datasets" library.

### CODE REVIEW

**Comment by d8ahazard** [comment]
OK, sorry, I honestly didn't mean to just start fixing "all the things", but I'm working on Windows (just to test the model stuff), and after looking at the code, I realized it probably doesn't *have* to be linux-only.

**Comment by vinesmsuic** [comment]
Hi, really appreciate the effort for fixing the issues! I am now reviewing the changes and will try to get it merged.

**Review by vinesmsuic — APPROVED** [review]

**Comment by d8ahazard** [comment]
> Hi, really appreciate the effort for fixing the issues! I am now reviewing the changes and will try to get it merged.

I may still have some fixing to do. Trying to use an exported wheel of this, I'm getting an issue importing MODEL_PATH. yet. Might need to make it a separate file.

**Comment by vinesmsuic** [comment]
Just got merged. Thanks for the code improvement! We will extend the codebase in the future, following a similar ecosystem of [ImagenHub](https://github.com/TIGER-AI-Lab/ImagenHub).

**Pull request merged**
